# Profil HOMOLOGATION (préproduction)
spring.application.name=messaging

# PostgreSQL JDBC - Homologation
spring.datasource.url=jdbc:postgresql://hom-db.internal:5432/messaging_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# IBM MQ - Homologation
app.mq.queue-manager=HOM_QM1
app.mq.channel=HOM.APP.SVRCONN
app.mq.conn-name=hom-mq.internal(1414)
app.mq.username=${MQ_USERNAME}
app.mq.password=${MQ_PASSWORD}
app.mq.inbound-queue=HOM.QUEUE.1
app.mq.outbound-queue=HOM.QUEUE.1

# JMS resilience tuning
spring.jms.listener.session.acknowledge-mode=auto
spring.jms.listener.min-concurrency=5
spring.jms.listener.max-concurrency=15

# Logging
logging.level.root=WARN
logging.level.com.example.messaging=INFO

