spring.application.name=messaging

# Profil par defaut : dev (peut etre override)
spring.profiles.active=dev

# PostgreSQL JDBC (driver)
spring.datasource.driver-class-name=org.postgresql.Driver

# PostgreSQL JDBC - Default (dev)
spring.datasource.url=jdbc:postgresql://localhost:5432/messaging_db
spring.datasource.username=messaging_user
spring.datasource.password=messaging_password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# IBM MQ - Default (dev)
app.mq.queue-manager=QM1
app.mq.channel=DEV.APP.SVRCONN
app.mq.conn-name=localhost(1414)
app.mq.username=app
app.mq.password=passw0rd
app.mq.inbound-queue=DEV.QUEUE.1
app.mq.outbound-queue=DEV.QUEUE.1

# JMS resilience tuning
spring.jms.listener.session.acknowledge-mode=auto
spring.jms.listener.min-concurrency=3
spring.jms.listener.max-concurrency=10

